name: Build Kernel - A15

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
      include_susfs:
        required: true
        type: boolean
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
        default: ""

jobs:
  build-kernels-a15:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "30"
          #  os_patch_level: "2024-08"
          #- sub_level: "46"
          #  os_patch_level: "2024-09"
          - sub_level: "50"
            os_patch_level: "2024-10"
          - sub_level: "56"
            os_patch_level: "2024-11"
          - sub_level: "57"
            os_patch_level: "2024-12"
          - sub_level: "58"
            os_patch_level: "2025-01"
          - sub_level: "66"
            os_patch_level: "2025-02"
          - sub_level: "77"
            os_patch_level: "2025-03"
          - sub_level: "82"
            os_patch_level: "2025-04"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      include_susfs: ${{ inputs.include_susfs }}
