name: Build Kernel - A13

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
      include_susfs:
        required: true
        type: boolean
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
        default: ""

jobs:
  build-kernels-a13-5-10:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "234"
          #  os_patch_level: "2025-03"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android13"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      include_susfs: ${{ inputs.include_susfs }}

  build-kernels-a13-5-15:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "178"
          #  os_patch_level: "2025-03"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      include_susfs: ${{ inputs.include_susfs }}
